from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING: from .engine import Engine

class Callback:
    """
    回调基类。
    所有方法都接收 engine 实例，允许修改 engine 状态或读取数据。
    """
    def on_init(self, engine: Engine): ...
    
    def on_train_start(self, engine: Engine): ...
    def on_train_end(self, engine: Engine): ...
    
    def on_epoch_start(self, engine: Engine): ...
    def on_epoch_end(self, engine: Engine): ...
    
    def on_batch_start(self, engine: Engine): ...
    def on_batch_end(self, engine: Engine): ...
    
    def on_eval_start(self, engine: Engine): ...
    def on_eval_end(self, engine: Engine): ...

    def on_exception(self, engine: Engine): ...
    def on_train_interrupt(self, engine: Engine): ...